### PR TITLE
Implementation "Calculation" application

### PR DESCRIPTION
**Pull request by green1971weekend**
Added my first console version of calculator. Unfortunately I couldn't add the calculator project into my first created empty solution, because of the IDE didn't open the solution explorer for adding new projects. So, I decided create the same solution name through creating the new calc project, because if I got it correctly, IDE is making the solution connecting it with present project and I observed the further possibility for adding new projects into this solution.

### CODE REVIEW

**Comment by MikhailMasny** [comment]
Very informative description 💯 
And maybe you can called PR: Implementation "Calculation" application ?

**Comment by MikhailMasny** [comment]
And i think you have troubles with Visual Studio solution.. Can you delete [this file](https://github.com/green1971weekend/TMS-dotNET-Str/blob/add-calc/Straltsou.TSM0209.sln) and added HelloWorld project to your current solution? And the last mistake is you add your project to root of repo.. You need replace it to src and after it you need to show it in VS solution explorer 2 projects, HelloWorld and SimpleCalc.

**Comment by green1971weekend** [comment]
Got it! Deleted the empty solution and added in current solution two projects: HelloWorld and SimpleCalc. 

You're right, this title of PR sounds better. Ready to approve?:)

**Review by MikhailMasny — APPROVED** [review]
Good job! Ready to close 👍

**Pull request merged**
